[package]
name = "aplang"
version = "0.1.0"
authors = ["Amejonah1200 <amejonah@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8.0"
