[package]
name = "aplang"
version = "0.1.0"
authors = ["Amejonah1200 <amejonah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
num-derive = "0.3.3"
predicates = "1.0.7"
