[package]
name = "aplang-typing"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
strum_macros.workspace = true
slotmap.workspace = true
aplang-parser.workspace = true